version: '3.8'

services:
  exporter:
    image: node:18-bullseye
    volumes:
      - ..:/workspace:cached,Z
    command: sleep infinity

  ispyb:
    build:
      context: .
      dockerfile: Dockerfile.ispyb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
